### ISSUE TITLE
Sourcify integration

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/blockscout#8]
Contract Sourcecode upload have always been one of the top pain points when it comes to managing a blockscout instance.

Sourcify targets this problem https://sourcify.dev/ and Blockscout has integrated support for that in 3.7.0:
seen env-variables:
```
ENABLE_SOURCIFY_INTEGRATION
SOURCIFY_SERVER_URL
SOURCIFY_REPO_URL
```
this could solve: https://github.com/DMDcoin/hbbft-posdao-contracts/issues/32  in a lot of cases, or make it easier to implement.

**Comment by SurfingNerd** [comment]
This error comes from Sourcify interface ?!
```
2021-12-06T19:33:18.928 [error] #PID<0.2782.0> running BlockScoutWeb.Endpoint (connection #PID<0.2781.0>, stream id 1) terminated
Server: explorer.uniq.diamonds:80 (http)
Request: POST /verify_smart_contract/contract_verifications
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:error, %{"errors" => [%{"field" => "chain", "message" => "Chain 777012 not supported!"}], "message" => "Validation Error: chain"}}
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_verification_controller.ex:107: BlockScoutWeb.AddressContractVerificationController.verify_and_publish/3
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_verification_controller.ex:83: BlockScoutWeb.AddressContractVerificationController.create/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_verification_controller.ex:1: BlockScoutWeb.AddressContractVerificationController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_verification_controller.ex:1: BlockScoutWeb.AddressContractVerificationController.phoenix_controller_pipeline/2
        (phoenix 1.5.6) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 0.0.1) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
        (block_scout_web 0.0.1) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint."call (overridable 3)"/2
        (block_scout_web 0.0.1) lib/spandex_phoenix.ex:156: BlockScoutWeb.Endpoint.call/2
```

**Comment by SurfingNerd** [comment]
closed in favor of: https://github.com/DMDcoin/blockscout/issues/17
